### PR TITLE
AppControl Manager v1.5.0.0

### LINKED ISSUE #412: [Bug]: `New-SupplementalWDACConfig -Certificates` throws XML error "The element 'AllowedSigners' in namespace 'urn:schemas-microsoft-com:sipolicy' has incomplete content"
### Tools category

WDACConfig Module

### Does Your System Meet The Requirements?

- [X] Yes, I acknowledge that I've read the requirements and my system meets them. 👍

### Is your Windows Installation Genuine?

- [X] Yes, I acknowledge that the installation media of the Windows OS I used the tool on was downloaded from the official Microsoft website and I didn't tamper or modify it. 💯

### Did You Read The Frequently Asked Questions?

- [X] Yes, I've referred to the [FAQs](https://github.com/HotCakeX/Harden-Windows-Security/wiki/Answers-to-the-Basic-Frequently-Asked-Questions) and my issue is not covered/explained in there.

### Please Explain The Bug

Hi @HotCakeX,

thank you very, very much for your tremendous amount of work securing the windows OS landscape. I'm using some of your collected wisdom to protect my clients successfully. The official docs on WDAC are not very insightful and good tutorials for WDAC are scarce, so thank you😀

I'm having trouble creating supplemental policies from existing certificates.

In this example I'm using the WireGuard Authenticode Cert (extracted from the original MSI) and want to add this cert to a new supplemental policy.
Happens both on Win 11 23H2 en-us (VM) and Win 11 24H2 de-de (fresh install).

```powershell
New-WDACConfig -PolicyType AllowMicrosoft -EnableScriptEnforcement
New-SupplementalWDACConfig -Certificates -CertificatePaths "C:\MDM\8BC932FDFF15B892E8364C49B383210810E4709D.cer" -SuppPolicyName 'TrustedPublishers' -PolicyPath "C:\Program Files\WDACConfig\AllowMicrosoft.xml" -SigningScenario UserMode

> The file 'SupplementalPolicy TrustedPublishers.xml' has been saved in 'C:\Program Files\WDACConfig'
> The file 'SupplementalPolicy TrustedPublishers.cip' has been saved in 'C:\Program Files\WDACConfig'
> Exception: Exception calling "Set" with "5" argument(s): "Validation error in C:\Program Files\WDACConfig\StagingArea\New-SupplementalWDACConfig\SupplementalPolicy TrustedPublishers.xml: Validation error in C:\Program 
Files\WDACConfig\StagingArea\New-SupplementalWDACConfig\SupplementalPolicy TrustedPublishers.xml: The element 'AllowedSigners' in namespace 'urn:schemas-microsoft-com:sipolicy' has incomplete content. List of
possible elements expected: 'AllowedSigner' in namespace 'urn:schemas-microsoft-com:sipolicy'."
```

This results in an error (see attached error details field).

I did encounter similar errors before, when building my WDAC policies using only the official powershell commands.

Certain operations using the WDAC commands made the resulting XML invalid and further operations couldn't continue until the XML was manually fixed:

```powershell
# Using a copy of latest user mode block list
$fileUserModeBlockList = 'C:\MDM\usermodeblocklist.xml'
# Remove 'allow all rules' from user mode block policy
# Remove 'allow all rules' from user mode block policy
Remove-CIPolicyRule -FilePath $fileUserModeBlockList -Id "ID_ALLOW_A_1"
Remove-CIPolicyRule -FilePath $fileUserModeBlockList -Id "ID_ALLOW_A_2"
# Fix broken XML (from previous step)
$xmlDoc = [xml](Get-Content $fileUserModeBlockList)
$xmlDoc.SiPolicy.SigningScenarios.ChildNodes | Where-Object { $_.ID -eq 'ID_SIGNINGSCENARIO_WINDOWS' } | ForEach-Object { [void]$_.ChildNodes.RemoveAll() }
$xmlDoc.Save((Resolve-Path $fileUserModeBlockList))
...
[further operations]
...
```

Is this issue something that you can reproduce or maybe I am using your tools wrong?

Greetings
Denis

### Error Details

```console
PS C:\Users\it> Get-Error | fl *

Exception             : System.Management.Automation.MethodInvocationException: Exception calling "Set" with "5" argument(s): "Validation error in C:\Program
                        Files\WDACConfig\StagingArea\New-SupplementalWDACConfig\SupplementalPolicy Trusted Publishers.xml: Validation error in C:\Program
                        Files\WDACConfig\StagingArea\New-SupplementalWDACConfig\SupplementalPolicy Trusted Publishers.xml: The element 'AllowedSigners' in namespace 'urn:schemas-microsoft-com:sipolicy'
                        has incomplete content. List of possible elements expected: 'AllowedSigner' in namespace 'urn:schemas-microsoft-com:sipolicy'."
                         ---> System.InvalidOperationException: Validation error in C:\Program Files\WDACConfig\StagingArea\New-SupplementalWDACConfig\SupplementalPolicy Trusted Publishers.xml: Validation
                        error in C:\Program Files\WDACConfig\StagingArea\New-SupplementalWDACConfig\SupplementalPolicy Trusted Publishers.xml: The element 'AllowedSigners' in namespace
                        'urn:schemas-microsoft-com:sipolicy' has incomplete content. List of possible elements expected: 'AllowedSigner' in namespace 'urn:schemas-microsoft-com:sipolicy'.
                           at WDACConfig.CiPolicyTest.TestCiPolicy(String xmlFilePath, String cipFilePath)
                           at WDACConfig.SetCiPolicyInfo.Set(String filePath, Nullable`1 resetPolicyID, String policyName, String basePolicyID, String basePolicyToSupplementPath)
                           at CallSite.Target(Closure, CallSite, Type, FileInfo, Boolean, String, Object, Object)
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                           at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
TargetObject          :
CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
FullyQualifiedErrorId : InvalidOperationException
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at New-SupplementalWDACConfig<Process>, C:\Program Files\PowerShell\Modules\WDACConfig\0.4.9\Core\New-SupplementalWDACConfig.psm1: line 336
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
```

### LINKED ISSUE #414: [Bug]: AppControl Manager doesn't remember window size
### Tools category

AppControl Manager app

### Does Your System Meet The Requirements?

- [X] Yes, I acknowledge that I've read the requirements and my system meets them. 👍

### Is your Windows Installation Genuine?

- [X] Yes, I acknowledge that the installation media of the Windows OS I used the tool on was downloaded from the official Microsoft website and I didn't tamper or modify it. 💯

### Did You Read The Frequently Asked Questions?

- [X] Yes, I've referred to the [FAQs](https://github.com/HotCakeX/Harden-Windows-Security/wiki/Answers-to-the-Basic-Frequently-Asked-Questions) and my issue is not covered/explained in there.

### Please Explain The Bug

Every time you start AppControl Manager, the window size is reset. It doesn't remember the previous window size from last run.

Thank you.

### Error Details

_No response_

### PR DESCRIPTION
**Pull request by HotCakeX**
# What's New

* 🎉 Added a new page that lets you easily build a code signing certificate to be used for AppControl policy signing. It offers various options to configure the certificate such as key size, common name and validity.

* 🎉 Added a new page to create Supplemental policies. With this update, you can create supplemental policies by scanning files and folders, or by selecting certificates. More methods will be added in the future such as installed packaged apps and file paths with wildcards. Closes #412 

* 🎉 Added a new page that lets you select XML files and CIP binary files to deploy on the system.

* Added a new section to the Update page that will be displayed when a new version is available. It will display a link to the GitHub releases to show you the release notes.

* Added a new option to the Update page that will offer hardened updating procedure. When this option is enabled, the temporary private key of the on-device generated certificate will be linked to the user's account, requiring confirmation of prompts before it can be used for signing.

* 🎉 You can now select a MSIX file path in the Update page to use as the update source instead of downloaded it automatically. You could use this new section if you already downloaded the MSIX package from GitHub or you've built the app yourself from the source code.

* AppControl Manager is now [long path aware](https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation), it can use file paths longer than 260 characters.

* Improved the user experience when interacting with settings cards UI elements.

* When trying to enter a certificate common name in the settings page, the text box now automatically suggests you all the available common names to choose from. You no longer need to manually type anything. There is also a refresh button that fetches the latest changes to the certificates if you need to update the suggestions.

* The system information page will now let you remove supplemental policies from the system with 1 click/tap of a button, just like unsigned policies.

* 🎉 The app now remembers the window size (including maximized state) when closed, ensuring it reopens with the same size/state next time. Closes #414 

* Added a notice to the settings page -> Appearance section about Windows animations being disabled: https://github.com/HotCakeX/Harden-Windows-Security/issues/415

* Set the default path for file and folder pickers to the "WDACConfig" folder in Program Files, instead of the Documents folder. This can reduce the number of clicks user have to use to browse for policies, certificates etc.

* Added link to X in the about page's links section.

### CODE REVIEW

**Comment by WildByDesign** [comment]
Before I file a bug report I wanted to confirm something first.

You wrote `Improved the user experience when interacting with various UI elements` in the bullet points.

Does this fix the janky scroll bars in the section that shows all of the policies?

I didn’t see an associated bug report. But basically the scroll bars fail to work at all approx. 80% of the time in this section. They just stop working and become very difficult to get them to appear again.

**Comment by WildByDesign** [comment]
> Can you please record a quick video to show me the problem?

Absolutely. But I am on my phone right now so I won’t be able to do it until later in the day.

The problem for me is with the horizontal scroll bar on the bottom. I don’t have enough policies to bring up the vertical scroll bar but I can try later.

I will record a small video for you but I just can’t do it for a few more hours.

**Comment by HotCakeX** [comment]
> > Can you please record a quick video to show me the problem?
> 
> Absolutely. But I am on my phone right now so I won’t be able to do it until later in the day.
> 
> The problem for me is with the horizontal scroll bar on the bottom. I don’t have enough policies to bring up the vertical scroll bar but I can try later.
> 
> I will record a small video for you but I just can’t do it for a few more hours.

Oh it's okay, no rush, 
btw if you check the box for system policies you will see a lot of them

**Comment by WildByDesign** [comment]
I created a bug report (https://github.com/HotCakeX/Harden-Windows-Security/issues/415) and added an animated gif while reproducing the issue.

The issue triggers all the time if you only have a few policies showing (and lots of blank space in the list view). If the entire list view is full of policies, the issue does not trigger as often. Although it does still trigger when full as well, it's just not as noticeable.

**Pull request merged**
