### PR TITLE
Harden Windows Security Module v0.4.8

### PR DESCRIPTION
**Pull request by HotCakeX**
# What's New

* Improved the execution speed of [Confirm-SystemCompliance](https://github.com/HotCakeX/Harden-Windows-Security/wiki/Harden%E2%80%90Windows%E2%80%90Security%E2%80%90Module#confirm-systemcompliance). I once improved it [in version 0.4.5](https://github.com/HotCakeX/Harden-Windows-Security/releases/tag/Hardening-Module-v.0.4.5) but this time it's become even faster.

boo

* Provided [Intune policy files](https://github.com/HotCakeX/Harden-Windows-Security/tree/main/Intune%20Files) for the remaining categories.
  * Use [this post](https://github.com/HotCakeX/Harden-Windows-Security/wiki/Microsoft-Graph-Explorer-and-API-Basics) as a getting started guide.

* Fixed compliance checking total displayed number. It would show an increased total number after the first run in the same session.

* Updated the [BitLocker wiki page](https://github.com/HotCakeX/Harden-Windows-Security/wiki/BitLocker,-TPM-and-Pluton-%7C--What-Are-They-and-How-Do-They-Work) with additional info regarding key protector setup using Intune and Group Policy.

### CODE REVIEW

**Comment by agpt8** [comment]
The confirm-systemcompliance still has a few issues where on freshly opened admin powershell, it will show a total item count of 266. And on subsequent runs, the item count would increase to 293, then 320, then 347 and so on. I dont have screenshots or screen recording as I did a fresh install of the system and still in the process of setting it up.

Also, there still mixed cases displayed for true and false values.

**Comment by HotCakeX** [comment]
> The confirm-systemcompliance still has a few issues where on freshly opened admin powershell, it will show a total item count of 266. And on subsequent runs, the item count would increase to 293, then 320, then 347 and so on. I dont have screenshots or screen recording as I did a fresh install of the system and still in the process of setting it up.
> 
> Also, there still mixed cases displayed for true and false values.

I fixed that issue about displayed numbers in this PR, what are the mixed results you're seeing?

**Comment by HotCakeX** [comment]
@agpt8 I can explain any of the results but in general the **Compliant** column/property means whether the setting is compliant with the logic implemented in the module or not. The **Value** column/property indicates the current value of the setting. The value can be anything as long as it is compliant. It's normal if the Compliant property shows true but the Value shows 0, false or none.

**Comment by agpt8** [comment]
By mixed cases I meant the true and false values are shown in a mix of 'true' , 'True', 'false' and 'False'.

Minor issue but since it was addressed in the last PR, it didn't fix the issue entirely. The mixed cases were less common but they were there.

**Comment by HotCakeX** [comment]
> By mixed cases I meant the true and false values are shown in a mix of 'true' , 'True', 'false' and 'False'.
> 
> Minor issue but since it was addressed in the last PR, it didn't fix the issue entirely. The mixed cases were less common but they were there.

Oh i see now, the first letter for all of them should be upper case, will take care of it in the next update!

**Pull request merged**
