### PR TITLE
Harden Windows Security v0.5.5

### LINKED ISSUE #282: Full GUI experience for Harden Windows Security Module
The Harden Windows Security module will have full GUI experience, including all of its cmdlets and features.

- [x] Applying protection through the GUI
- [x] Performing Audit and compliance checking through the GUI
- [x] New modern tooltips for the entire GUI
- [x] Removing protection through the GUI
- [x] Modifying individual ASR rules through the GUI
- [ ] BitLocker activation and enrollment through the GUI

### LINKED ISSUE #318: [Bug]: RuntimeBroker.exe StrictCFG not compatible with Windows 11 on ARM hardware (virtualized)
### Tools category

Harden Windows Security Module

### Does Your System Meet The Requirements?

- [X] Yes, I acknowledge that I've read the requirements and my system meets them. 👍

### Is your Windows Installation Genuine?

- [X] Yes, I acknowledge that the installation media of the Windows OS I used the tool on was downloaded from the official Microsoft website and I didn't tamper or modify it. 💯

### Did You Read The Frequently Asked Questions?

- [X] Yes, I've referred to the [FAQs](https://github.com/HotCakeX/Harden-Windows-Security/wiki/Answers-to-the-Basic-Frequently-Asked-Questions) and my issue is not covered/explained in there.

### Please Explain The Bug

After enabling "some unknown" setting, when I opened the Start menu and typed, it would not show the search GUI. Also the search bar on the taskbar does nothing.

Reset my VM, ran Windows Update, enabled Smart App Control, and applied the rules one by one starting from the bottom, rebooting every time in between. Attack Surface Reduction breaks the search GUI. 

Not sure how to proceed from here. Maybe I'll have some more time to look into this later. It is of course a Microsoft bug. This is inside an UTM (Apple M1) VM. So no virtualisation based security (no nested VMs). Might be relevant.

August 2024 Windows Updates installed (of course).

### Error Details

```console
N/A
```

### PR DESCRIPTION
**Pull request by HotCakeX**
# What's New

* Added Compliance checking and system auditing functionality to the GUI with built-in search functionality.

* Added Sidebar tabbed experience with animation for ease of use. It has virtually unlimited space for new features and pages with scrollable style.

* Using [MVVM](https://learn.microsoft.com/en-us/dotnet/architecture/maui/mvvm) design pattern.

* Native WPF GUI with no 3rd party dependency or any compiled binaries.

* When ARM hardware is detected, all process mitigations will be skipped. [More info here](https://github.com/HotCakeX/Harden-Windows-Security/issues/318). If you have ARM hardware and want to contribute to this project, you can help me verify each process mitigation on your ARM hardware so I can enable the ones that are compatible.

* The experience and logic for enabling logging has been improved.

* You can now manually enter the path where the logs will be saved to as well. Previously, you'd only have to use the button on the GUI to browse for one.

* Added custom tooltips for each category and sub-category in the protection tab with small meaningful details to help you decide which option to choose.

* Required PowerShell version has been increased from 7.4.2 to 7.4.4. The Harden Windows Security heavily relies on the latest .NET components shipped with PowerShell, that's why you don't need to install .NET runtime separately.

* When logging is enabled, the logs are written to the file in real time instead of at the end of the operation.

* Significantly improved the toast notifications experience, they are now modern Windows 11 style toast notifications. Due to this improved experience, 5 official Microsoft-Signed DLLs are bundled with the Harden Windows Security program. Links to them can be found below:
  
    * [Microsoft.Toolkit.Uwp.Notifications](https://www.nuget.org/packages/Microsoft.Toolkit.Uwp.Notifications/)
    * [Microsoft.Win32.SystemEvents](https://www.nuget.org/packages/Microsoft.Win32.SystemEvents/)
    * [Microsoft.Windows.SDK.NET.Ref](https://www.nuget.org/packages/Microsoft.Windows.SDK.NET.Ref)
    * [System.Drawing.Common](https://www.nuget.org/packages/System.Drawing.Common/)

* The Harden Windows Security program can now be fully used in both Visual Studio (native C#) and Visual Studio Code (native PowerShell). Its hybrid design allows it to be highly interoperable.

<br>

## What's Next

* `Unprotect-WindowsSecurity` will be added to the GUI.

* Attack Surface Reduction rules will be individually configurable in a new section in the GUI.

* BitLocker enrollment and activation through the GUI.

* And more.

<br>

Resolves #318

<br>

### CODE REVIEW

**Comment by agpt8** [comment]
Getting this error after updating
image

**Comment by HotCakeX** [comment]
@agpt8 What do you see when you run these
```powershell
Import-module -Name 'Harden-Windows-Security-Module'
Get-Error
```

**Comment by agpt8** [comment]
image

**Comment by HotCakeX** [comment]
Not at all, i'm glad you let me know about these errors, but it's all okay, I've found the root cause of all of them and i apologize for letting them slip, i'll explain why

1. The first problem is caused by an outside program that i didn't use in my environment, for that i will detect if there is an interference with dll load and disable the new notifications experience.
2. The other error about Confirm-SystemCompliance command is [related to a known issue](https://github.com/PowerShell/PowerShell/issues/13866) with DISM command in PowerShell installed through Microsoft Store (Not from the MSI version). For that there is a workaround which is offloading the task to Windows PowerShell version of the DISM module.

I've rolled back the version file in the repo root that points to the new version, so that auto updating won't happen, i will release the new version with the fixes very soon.

P.S about the tooltips showing up quickly, I Intentionally made it that way because the default timing was too slow and I wanted users to quickly get the information about each category as they hover over them.

**Comment by HotCakeX** [comment]
@agpt8 released v0.5.6, please try again and let me know how it goes
https://github.com/HotCakeX/Harden-Windows-Security/releases/tag/Hardening-Module-v.0.5.6

**Comment by agpt8** [comment]
Everything looks good now! Confirm and Verify list is also populating in the GUI.
There are a few observations and suggestions I would like to highlight for the GUI. I'll open a discussion later today for all of those.
Thanks for the quick fix!

**Pull request merged**
